"""Constants for the Entidade Reguladora dos Serviços Energéticos integration."""

DOMAIN = "erse"
COUNTRY = "Portugal"
CONF_OPERATOR = "operator"
CONF_PLAN = "plan"
CONF_METER = "meter"
CONF_COST = "cost"
CONF_POWER_COST = "power_cost"
CONF_UTILITY_METER = "utility_meter"
CONF_UTILITY_METERS = "utility_meter"
